### ISSUE TITLE
A regression in MemoryLeakFix 0.5.4～0.5.1 causes Minecraft 1.18.1 to crash when Borderless Mining 1.1.1 is also installed.

### ISSUE THREAD

**Issue by akemin-dayo** [fxmorin/memoryLeakFix#30]
Version 0.3.5 is the last version of MemoryLeakFix that I've found to be unaffected by this regression.

Here's the stacktrace generated by 0.5.4 (Minecraft 1.18.1, Borderless Mining 1.1.1):

```
[02:20:49] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at link.infra.borderlessmining.config.ConfigHandler.isEnabled(ConfigHandler.java:123) ~[borderless-mining-1.1.1+1.18.jar:?]
	at net.minecraft.client.WindowSettings.handler$zei000$modifyInitialSettings(WindowSettings:534) ~[?:?]
	at net.minecraft.client.WindowSettings.<init>(WindowSettings:18) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:167) ~[fabric-loader-0.14.8-1.18.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at link.infra.borderlessmining.config.ConfigHandler.isEnabled(ConfigHandler.java:123) ~[borderless-mining-1.1.1+1.18.jar:?]
	at net.minecraft.client.WindowSettings.handler$zei000$modifyInitialSettings(WindowSettings:534) ~[?:?]
	at net.minecraft.client.WindowSettings.<init>(WindowSettings:18) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:167) ~[fabric-loader-0.14.8-1.18.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method freeByteBuffer(Ljava/io/File;IIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in memoryleakfix.mixins.json:hugeScreenshotLeak.MinecraftClient_screenshotMixin from mod memoryleakfix failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap memoryleakfix-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at link.infra.borderlessmining.config.ConfigHandler.isEnabled(ConfigHandler.java:123) ~[borderless-mining-1.1.1+1.18.jar:?]
	at net.minecraft.client.WindowSettings.handler$zei000$modifyInitialSettings(WindowSettings:534) ~[?:?]
	at net.minecraft.client.WindowSettings.<init>(WindowSettings:18) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:167) ~[fabric-loader-0.14.8-1.18.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
```

**Comment by FxMorin** [comment]
Oh interesting, should be fixed in the next release

**Comment by FxMorin** [comment]
Nevermind, can you please give me the mods list you where using

**Comment by akemin-dayo** [comment]
I'm able to reproduce this crash with having _only_ these mods enabled in Minecraft 1.18.1:
* [Fabric API 0.46.6+1.18](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3671143)
* [Borderless Mining 1.1.1+1.18](https://www.curseforge.com/minecraft/mc-mods/borderless-mining/files/3549245)
* [MemoryLeakFix 0.5.4](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix/files/3885684)

MemoryLeakFix 0.5.4 works fine with Minecraft 1.18.1 (and the rest of my usual mods list) as long as Borderless Mining 1.1.1 is _not_ present.

**Comment by FxMorin** [comment]
Alright I'll look into it

**Comment by FxMorin** [comment]
Ya so basically 1.18.1 was too unstable for >=0.3.5
If you get this issue with the latest version in either 1.19 or 1.18.2 then make a new issue
