### ISSUE TITLE
Crash with exit code 1 using 0.7.0 for MC 1.18.1

### ISSUE THREAD

**Issue by MordorsElite** [fxmorin/memoryLeakFix#38]
Cant say much else, since it doesn't give any specifics in the error message, just error code 1. The crash happens during startup.

I'll leave a list of all the mods used:

- Fabric loader 0.12.12
- fabric-api 0.46..1
- sodium 0.4.0
- iris 1.2.0
- indium 1.0.2
- starlight 1.0.0
- enhancedblockentities 0.5
- lazydfu 0.1.2
- ferritecore 4.1.2

Also a number of others, but those only add functionality and (to my knowledge) don't change fundamental game mechanics themselves

**Comment by FxMorin** [comment]
Please include the crash log of the game. It can be found in your `.minecraft/crash-reports` and if its not there, than include the latest log from `.minecraft/logs`

**Comment by thanhgaming5550** [comment]
I got it too: 
```
[07:52:30] [main/INFO]: Loading Minecraft 1.19.1 with Fabric Loader 0.14.8
[07:52:32] [ForkJoinPool-1-worker-4/WARN]: Mod nicephore uses the version fabric-1.19.x-1.0.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:52:35] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.4.6+mc1.19-build.47 recommends version 1.4.2 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.4.2 or later of reeses-sodium-options for the optimal experience.
[07:52:35] [main/INFO]: Loading 125 mods:
	- advancementinfo 1.19.1-fabric0.58.5-1.3.1
	- antighost 1.19.1-fabric0.58.5-1.1.5
	- appleskin 2.4.0+mc1.19
	- architectury 6.0.35
	- audio_engine_tweaks 1.2.3
	- badpackets 0.2.0
	- betterf3 1.3.2
	- biome_threadlocal_fix 1.3
	- bookshelf 15.0.1
	- boostedbrightness 2.1.2
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.73 via advancementinfo
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.0 via essential_commands
	- com_github_llamalad7_mixinextras 0.0.12 via debugify
	- com_profesorfalken_jpowershell 3.1.1 via nicephore
	- craftpresence 1.8.9
	- crowdin-translate 1.4+1.19 via antighost
	- customlan 1.19.1-v2.0.3
	- customstars 1.1+1.19
	- debugify 2.4.0
	- detailab 2.6.2+1.19-fabric
	- dev_isxander_settxi_settxi-core 2.5.3 via zoomify
	- dev_isxander_settxi_settxi-kotlinx-serialization 2.5.3 via zoomify
	- ec-core 1.2.1-mc1.19.1 via essential_commands
	- essential_commands 0.28.0-mc1.19.1
	- fabric 0.58.5+1.19.1
	- fabric-api-base 0.4.9+e62f51a395 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f4095 via fabric
	- fabric-biome-api-v1 9.0.15+d5533c0195 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f4095 via fabric
	- fabric-command-api-v1 1.2.9+f71b366f95 via fabric
	- fabric-command-api-v2 2.1.5+0c17ea9695 via fabric
	- fabric-commands-v0 0.2.26+df3654b395 via fabric
	- fabric-containers-v0 0.1.31+df3654b395 via fabric
	- fabric-content-registries-v0 3.2.1+07df213e95 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d2495 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4a95 via fabric
	- fabric-data-generation-api-v1 5.1.5+a680b9b495 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f78595 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f4095 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f4095 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b395 via fabric
	- fabric-game-rule-api-v1 1.0.19+1899036195 via fabric
	- fabric-item-api-v1 1.5.5+35a03c4395 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f4095 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f4095 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b395 via fabric
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.0+33fbc73895 via fabric
	- fabric-loot-api-v2 1.1.1+03a4e56895 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c695 via fabric
	- fabric-message-api-v1 5.0.1+4e0178f495 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc73895 via fabric
	- fabric-models-v0 0.3.15+9ff28f4095 via fabric
	- fabric-networking-api-v1 1.2.1+3082331495 via fabric
	- fabric-networking-v0 0.3.18+df3654b395 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f4095 via fabric
	- fabric-particles-v1 1.0.8+dc39553a95 via fabric
	- fabric-permissions-api-v0 0.2-SNAPSHOT via essential_commands
	- fabric-registry-sync-v0 0.9.21+23c4cfef95 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f4095 via fabric
	- fabric-renderer-indigo 0.6.10+5187d39f95 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b395 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f4095 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f4095 via fabric
	- fabric-rendering-v0 1.1.20+df3654b395 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f4095 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a395 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e095 via customlan
	- fabric-screen-api-v1 1.0.24+f05effaf95 via fabric
	- fabric-screen-handler-api-v1 1.2.10+9ff28f4095 via fabric
	- fabric-textures-v0 1.0.18+9ff28f4095 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a395 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c695 via fabric
	- fabricloader 0.14.8
	- fallingleaves 1.12.1+1.19
	- faster_entity_animations 1.5.3
	- ferritecore 4.2.1
	- forgeconfigapiport 4.1.4
	- freecam 1.1.4
	- indium 1.0.7+mc1.19
	- iris 1.2.6
	- java 17
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- lithium 0.8.3
	- memoryleakfix 1.19.1-0.7.0
	- minecraft 1.19.1
	- modmenu 4.0.5
	- morechathistory 1.1.1
	- nicephore fabric-1.19.x-1.0.0
	- openpartiesandclaims 0.8.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- phosphor 0.8.1
	- placeholder-api 2.0.0-beta.7+1.19 via essential_commands
	- playerabilitylib 1.6.0 via essential_commands
	- pride 1.1.2+1.19 via lambdynlights
	- replaymod 1.19.1-2.6.7
	- settxi-gui-cloth-config 2.5.3 via zoomify
	- shulkerboxtooltip 3.1.1+1.19
	- skinlayers 1.5.1-mc1.19.1
	- sleepbackground 2.3+1.14.x_to_1.19.x
	- sodium 0.4.2+replaymod.rev.bfbc6de
	- sodium-extra 0.4.6+mc1.19-build.47
	- spruceui 4.0.0+1.19 via lambdynlights
	- worldedit 7.2.11+c43a877
	- worldeditcui 1.19+01
	- xaerominimap 22.13.0
	- xaeroworldmap 1.26.2
	- zoomify 2.0.3
[07:52:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/PROGRAM/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[07:52:52] [main/INFO]: Compatibility level set to JAVA_16
[07:52:52] [main/INFO]: Compatibility level set to JAVA_17
[07:52:55] [main/INFO]: Preloading Debugify
[07:52:55] [main/INFO]: Done.
[07:52:56] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 1 override(s) found
[07:52:56] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[07:52:56] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[07:52:56] [main/INFO]: Loaded configuration file for Sodium Extra: 27 options available, 0 override(s) found
[07:52:58] [main/WARN]: Force disabled MC-228976 because it's conflicting with: lithium
[07:52:59] [main/INFO]: Disabling ModelUtilMixin as MemoryLeakFix is loaded.
[07:53:00] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[07:53:01] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[07:53:03] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[07:53:03] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[07:53:03] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[07:53:06] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[07:53:09] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[07:53:30] [main/INFO]: Building unoptimized datafixer
[07:53:34] [main/WARN]: @Redirect conflict. Skipping memoryleakfix.mixins.json:biomeTemperatureLeak.Biome_threadLocalMixin from mod memoryleakfix->@Redirect::useStaticThreadLocal(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; with priority 1000, already redirected by biome_threadlocal_fix.json:MixinBiome from mod biome_threadlocal_fix->@Redirect::temperatureCacheReplacer(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; with priority 1000
[07:53:34] [main/WARN]: @Redirect conflict. Skipping memoryleakfix.mixins.json:biomeTemperatureLeak.Biome_threadLocalMixin from mod memoryleakfix->@Redirect::useStaticThreadLocal(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; with priority 1000, already redirected by biome_threadlocal_fix.json:MixinBiome from mod biome_threadlocal_fix->@Redirect::temperatureCacheReplacer(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; with priority 1000
[07:53:34] [main/WARN]: @Redirect conflict. Skipping memoryleakfix.mixins.json:biomeTemperatureLeak.Biome_threadLocalMixin from mod memoryleakfix->@Redirect::useStaticThreadLocal(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; with priority 1000, already redirected by biome_threadlocal_fix.json:MixinBiome from mod biome_threadlocal_fix->@Redirect::temperatureCacheReplacer(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; with priority 1000
[07:53:34] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[Fabric%201.19.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Fabric%201.19.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1959 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1959$class_1960.method_30972(class_1959.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_39151(class_5478.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_39152(class_5478.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_30726(class_5478.java:721) ~[client-intermediary.jar:?]
	at net.minecraft.class_5504.method_40363(class_5504.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[Fabric%201.19.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Fabric%201.19.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1959$class_1960.method_30972(class_1959.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_39151(class_5478.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_39152(class_5478.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_30726(class_5478.java:721) ~[client-intermediary.jar:?]
	at net.minecraft.class_5504.method_40363(class_5504.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[Fabric%201.19.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Fabric%201.19.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector useStaticThreadLocal(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; in memoryleakfix.mixins.json:biomeTemperatureLeak.Biome_threadLocalMixin from mod memoryleakfix failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap memoryleakfix-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1959$class_1960.method_30972(class_1959.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_39151(class_5478.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_39152(class_5478.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_5478.method_30726(class_5478.java:721) ~[client-intermediary.jar:?]
	at net.minecraft.class_5504.method_40363(class_5504.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[Fabric%201.19.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Fabric%201.19.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
```
I tried delete `.minecraft/.fabric` and `.minecraft/config/fabric`, but it's not work

**Comment by FxMorin** [comment]
The versions are now correctly labelled
