### ISSUE TITLE
Crashes on boot after updating to the latest version of sodium

### ISSUE THREAD

**Issue by ChristopherHaws** [fxmorin/memoryLeakFix#44]
After updating to the latest version of Sodium, my game is crashing on launch when MemoryLeakFix is enabled. Here is the stacktrace:
```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline failed
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171)
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425)
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:30)
	at net.minecraft.client.main.Main.handler$cmg000$loadAllMixinsThenShouldRenderAsync(Main:526)
	at net.minecraft.client.main.Main.main(Main:220)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 26 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [sspb.mixins.json:sodium.MixinSmoothLightPipeline from mod sspb] from phase [DEFAULT] in config [sspb.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 29 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on setOffsetFieldAndReturn could not find any targets matching 'Lme/jellysquid/mods/sodium/client/model/light/smooth/SmoothLightPipeline;applyComplex(Lme/jellysquid/mods/sodium/client/model/light/smooth/AoNeighborInfo;Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lnet/minecraft/class_2338;Lnet/minecraft/class_2350;Lme/jellysquid/mods/sodium/client/model/light/data/QuadLightData;I)V' in me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline. Using refmap sodium-shadowy-path-blocks-refmap.json [PREINJECT Applicator Phase -> sspb.mixins.json:sodium.MixinSmoothLightPipeline from mod sspb -> Prepare Injections ->  -> redirect$ddd000$setOffsetFieldAndReturn(II)Z -> Parse]
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 29 more

```

**Comment by FxMorin** [comment]
Please include the entire log

**Comment by FxMorin** [comment]
Was this only MemoryLeakFix and sodium, since this does not look like it was caused by memory leak fix

**Comment by Timolino456** [comment]
Do not use Not Enough Crashes. It is known to cause issues and then making people think it was Sodium or another of JellySquid's mods because they appear in the stacktrace. Remove it, try again and if it still crashes, upload the new (entire) log file.

**Comment by OceanicWhitetipProductions** [comment]
Confirmed. [Sodium + Memory Leak Fix + Fabric API](https://paste.ee/p/ZfEsp) log also on [Sodium + Memory Leak Fix](https://paste.ee/p/jQyhi) only log. 

Same results with a un-modified fabric.mod.json, with a "depends": {... ..."minecraft": "1.19", fix to "1.19.2", as well as ">=1.19".

**Comment by ChristopherHaws** [comment]
For me, using [MemoryLeakFix - v0.7.0 for 1.19.1](https://modrinth.com/mod/memoryleakfix/version/v0.7.0) works, but [MemoryLeakFix - v0.7.0 for 1.19.x](https://modrinth.com/mod/memoryleakfix/version/v0.7.0-1.19) does not. I am running 1.19.2 of Minecraft, so the 1.19.x version seems like it should be the one that works.

**Comment by FxMorin** [comment]
Fixed this on modrinth
