### ISSUE TITLE
crashes client when start game.

### ISSUE THREAD

**Issue by MrJorman** [fxmorin/memoryLeakFix#70]
[08:44:10] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at pro.gravit.launcher.aPalICeYZF7GV0.apALICezwkN5G1(Unknown Source) ~[Apalice.exe:?]
	at pro.gravit.launcher.aPalICeYZF7GV0.main(Unknown Source) ~[Apalice.exe:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) ~[fabric-loader-0.14.12.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:30) ~[memoryleakfix-1.19.1-0.7.0.jar:?]
	at net.minecraft.client.main.Main.handler$dap000$loadAllMixinsThenShouldRenderAsync(Main.java:1026) ~[minecraft.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:220) ~[minecraft.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 5 more
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.fabricmc.fabric.impl.blockrenderlayer.BlockRenderLayerMapImpl.initialize(BlockRenderLayerMapImpl.java:92) ~[fabric-blockrenderlayer-v1-1.1.2+c6af733c90-75d9a2ec107bde80.jar:?]
	at net.minecraft.class_4696.handler$bie000$onInitialize(class_4696.java:1546) ~[client-intermediary.jar:?]
	at net.minecraft.class_4696.<clinit>(class_4696.java:302) ~[client-intermediary.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) ~[fabric-loader-0.14.12.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:30) ~[memoryleakfix-1.19.1-0.7.0.jar:?]
	at net.minecraft.client.main.Main.handler$dap000$loadAllMixinsThenShouldRenderAsync(Main.java:1026) ~[minecraft.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:220) ~[minecraft.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	... 5 more

**Comment by litoj** [comment]
I have the same problem, using 1.19.3.

**Comment by fxmorin** [comment]
Another mod is attempting to force load all mixins. I need a full log, this mod should be making sure that memoryleakfix is not loaded before doing so.
Might also be the launcher

**Comment by FxMorin** [comment]
I'm going to need a full log to be able to do anything about this
