### ISSUE TITLE
Fabric 1.19.2 Error on Clear Caching. (Only Log)

### ISSUE THREAD

**Issue by suerion** [fxmorin/memoryLeakFix#73]
Hey, we got allways this error.

```[20:02:16] [Server thread/INFO]: [MemoryLeakFix] Attempting to ForceLoad All Mixins and clear cache
[20:02:16] [Server thread/INFO]: Mixing common.MixinServerStatusSerializer from nochatreports.mixins.json into net.minecraft.class_2926$class_2929
[20:02:16] [Server thread/INFO]: [STDERR]: java.lang.NoSuchFieldException: NO_GROUP
[20:02:16] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2642)
[20:02:16] [Server thread/INFO]: [STDERR]: 	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:32)
[20:02:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$fnn000$memoryleakfix$onFinishedLoadingWorlds(MinecraftServer.java:16770)
[20:02:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330)
[20:02:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3823(class_3176.java:172)
[20:02:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
[20:02:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[20:02:16] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:02:16] [Server thread/INFO]: [MemoryLeakFix] Done ForceLoad and clearing SpongePowered cache

**Comment by FxMorin** [comment]
I need the full log

**Comment by suerion** [comment]
@fxmorin hey sorry, had not seen the comment.
Here the full log, the error occurs only after the serverstartup, you need only look on  11:20:55
https://pastebin.com/JbHQd2Vc

**Comment by duakc** [comment]
I also met the issue 
Here is the full log:https://kirk.cdkm.com/convert/file/st3o4wam1bxhnvwixmu22hscxisqrrbm/latest.txt

**Comment by FxMorin** [comment]
It's already fixed internally. I will be releasing a fix with an experimental version of the mod soon

**Comment by suerion** [comment]
Hey, thanks for your work :)

**Comment by FxMorin** [comment]
This has been fixed in the betas
