### ISSUE TITLE
1.19.3 error

### ISSUE THREAD

**Issue by vaniron** [fxmorin/memoryLeakFix#79]
with 0.8.0 version of the plugin: 

[02:11:59] [Server thread/INFO]: [MemoryLeakFix] Attempting to ForceLoad All Mixins and clear cache
[02:11:59] [Server thread/INFO]: [STDERR]: java.lang.NoSuchFieldException: NO_GROUP
[02:11:59] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[02:11:59] [Server thread/INFO]: [STDERR]:      at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:32)
[02:11:59] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$bgo000$memoryleakfix$onFinishedLoadingWorlds(MinecraftServer.java:5793)
[02:11:59] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:338)
[02:11:59] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.method_3823(class_3176.java:169)
[02:11:59] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:648)
[02:11:59] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
[02:11:59] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)

Full log: https://pastebin.com/raw/qjNwEZ2w

**Comment by gabriel-andreescu** [comment]
I'm also having this error

**Comment by FxMorin** [comment]
I'm aware and it will be fixed in the refactor. 
You can downgrade your fabric loader version to temporarily fix this

**Comment by FxMorin** [comment]
This has been fixed in the betas
