### ISSUE TITLE
Soft crash at startup

### ISSUE THREAD

**Issue by Herobattler** [fxmorin/memoryLeakFix#91]
20:18:32.357
game
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:18:32.357
game
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
20:18:32.357
game
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:18:32.357
game
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
20:18:32.357
game
at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.7/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
20:18:32.357
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
20:18:32.357
game
... 7 more
20:18:32.357
game
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
20:18:32.357
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
20:18:32.357
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
20:18:32.357
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
20:18:32.357
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
20:18:32.357
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
20:18:32.357
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
20:18:32.357
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
20:18:32.357
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
20:18:32.357
game
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
20:18:32.357
game
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
20:18:32.357
game
at TRANSFORMER/patchouli@1.19.2-77/vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23)
20:18:32.357
game
at TRANSFORMER/minecraft@1.19.2/net.minecraft.SystemReport.handler$col000$patchouli_addContext(SystemReport.java:1016)
20:18:32.357
game
at TRANSFORMER/minecraft@1.19.2/net.minecraft.SystemReport.<init>(SystemReport.java:58)
20:18:32.357
game
at TRANSFORMER/minecraft@1.19.2/net.minecraft.CrashReport.<init>(CrashReport.java:31)
20:18:32.357
game
at TRANSFORMER/minecraft@1.19.2/net.minecraft.CrashReport.m_127529_(CrashReport.java:215)
20:18:32.357
game
at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:144)
20:18:32.357
game
at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
20:18:32.357
game
... 13 more
20:18:32.357
game
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method memoryLeakFix$captureByteBuffer(Ljava/nio/ByteBuffer;Lcom/llamalad7/mixinextras/sugar/ref/LocalRef;)Ljava/nio/ByteBuffer; in memoryleakfix.mixins.json:hugeScreenshotLeak.Minecraft_screenshotMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap memoryleakfix-common-1.17+-common-refmap.json
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
20:18:32.357
game
at TRANSFORMER/MixinExtras.beta._5@0.2.0-beta.5/com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.doPostInject(SugarWrapperInjectionInfo.java:131)
20:18:32.357
game
at TRANSFORMER/MixinExtras.beta._5@0.2.0-beta.5/com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.postInject(SugarWrapperInjectionInfo.java:125)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
20:18:32.357
game
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
20:18:32.357
game
... 33 more

**Comment by 5stigma** [comment]
same problem :/

**Comment by 5stigma** [comment]
in 1.18.2 version

**Comment by FxMorin** [comment]
Should be fixed in beta 5
