### ISSUE TITLE
MemoryLeakFix 1.0.0-beta.4 fails mixin injection on 1.17.1, 1.18.1 (Fabric), 1.18.2 (Quilt/Fabric), 1.19, 1.19.1, 1.19.2, 1.19.3, and 1.19.4 (Quilt/Fabric/Forge).

### ISSUE THREAD

**Issue by akemin-dayo** [fxmorin/memoryLeakFix#95]
MemoryLeakFix 1.0.0-beta.4 fails mixin injection on 1.17.1, 1.18.1 (Fabric), 1.18.2 (Quilt/Fabric), 1.19, 1.19.1, 1.19.2, 1.19.3, and 1.19.4 (Quilt/Fabric/Forge).

1.16.5 (Fabric) is **not** affected.

There are two main mixin injection failures I've come across in testing:
* `hugeScreenshotLeak` fails mixin injection for `memoryLeakFix$captureByteBuffer` in `net.minecraft.class_310` on the following versions and mod loaders:
	* 1.17.1 (Fabric)
		* ※ Forge is probably affected too, but this cannot be tested due to issue #97.
	* 1.18.1 (Fabric)
		* ※ Forge is probably affected too, but this cannot be tested due to issue #97.
	* 1.18.2 (Fabric)
		* ※ Forge is probably affected too, but this cannot be tested due to issue #97.
	* 1.19 (Quilt/Fabric/Forge)
	* 1.19.1 (Quilt/Fabric/Forge)
	* 1.19.2 (Quilt/Fabric/Forge)
	* 1.19.3 (Quilt/Fabric/Forge)
	* 1.19.4 (Quilt/Fabric/Forge)

* `tagKeyLeak` fails mixin injection for `useWeakInterner()` in `net.minecraft.class_6862` on the following versions and mod loaders:
	* 1.18.2 (Quilt)

I have confirmed that this reproduces with a minimal mod set consisting of just:
* Fabric Loader `0.14.18`
* Quilt Loader `0.18.6`
* Fabric API
	* `0.46.1+1.17` (1.17.1)
	* `0.46.6+1.18` (1.18.1)
	* `0.76.0+1.18.2` (1.18.2)
	* `0.58.0+1.19` (1.19)
	* `0.58.5+1.19.1` (1.19.1)
	* `0.76.0+1.19.2` (1.19.2)
	* `0.76.0+1.19.3` (1.19.3)
	* `0.76.0+1.19.4` (1.19.4)
* Quilt QFAPI
	* `qfapi-1.0.0-beta.28_qsl-1.1.0-beta.26_fapi-0.67.0_mc-1.18.2` (1.18.2)
	* `qfapi-2.0.0-beta.9_qsl-2.0.0-beta.16_fapi-0.58.0_mc-1.19` (1.19)
	* `qfapi-4.0.0-beta.6_qsl-3.0.0-beta.10_fapi-0.58.5_mc-1.19.1` (1.19.1)
	* `qfapi-4.0.0-beta.29_qsl-3.0.0-beta.29_fapi-0.75.1_mc-1.19.2` (1.19.2)
	* `qfapi-5.0.0-beta.8_qsl-4.0.0-beta.12_fapi-0.75.1_mc-1.19.3` (1.19.3)
	* `qfapi-6.0.0-beta.2_qsl-5.0.0-beta.1_fapi-0.76.0_mc-1.19.4` (1.19.4)
* Forge
	* `41.0.63` (1.19)
	* `42.0.9` (1.19.1)
	* `43.1.1` (1.19.2)
	* `44.1.23` (1.19.3)
	* `45.0.23` (1.19.4)
* MemoryLeakFix `1.0.0-beta.4` (※ `fabric.mod.json` has been modified to work around issue #94.)

## Stack trace for `hugeScreenshotLeak`, `memoryLeakFix$captureByteBuffer`, `net.minecraft.class_310` (Quilt/Fabric)
※ This example is specifically taken from Fabric 1.17.1, but the stack traces are all pretty similar for other affected versions so I'm just showing this one for the sake of brevity.

Stacktraces for some other versions can be found in the edit history of this post. I removed them since it was getting kinda… long.
```
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.18.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:187) ~[fabric-loader-0.14.18-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:187) ~[fabric-loader-0.14.18-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method memoryLeakFix$captureByteBuffer(Ljava/nio/ByteBuffer;Lcom/llamalad7/mixinextras/sugar/ref/LocalRef;)Ljava/nio/ByteBuffer; in memoryleakfix.mixins.json:hugeScreenshotLeak.Minecraft_screenshotMixin from mod memoryleakfix failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap memoryleakfix-common-1.17+-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.doPostInject(SugarWrapperInjectionInfo.java:131) ~[com_github_llamalad7_mixinextras.2.0-beta.5-47a0e55a7b7247cc.jar:?]
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.postInject(SugarWrapperInjectionInfo.java:125) ~[com_github_llamalad7_mixinextras.2.0-beta.5-47a0e55a7b7247cc.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:187) ~[fabric-loader-0.14.18-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 2 more
```

## Stack trace for `tagKeyLeak`, `useWeakInterner()`, `net.minecraft.class_6862` (Quilt 1.18.2)
```
Mixin transformation of net.minecraft.class_6862 failed
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:451) ~[quilt-loader-0.18.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:246) ~[quilt-loader-0.18.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.18.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.18.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.18.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2874.method_28522(class_2874.java:70) ~[transformed-mod-minecraft.i0:0/:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_2874.<clinit>(class_2874.java:56) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5843$class_5845.<clinit>(class_5843.java:59) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5843.<clinit>(class_5843.java:11) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_6122.<clinit>(class_6122.java:12) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:13) ~[transformed-mod-minecraft.i0:0/:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:153) [transformed-mod-minecraft.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) [quilt-loader-0.18.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) [quilt-loader-0.18.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.18.6.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector useWeakInterner()Lcom/google/common/collect/Interner; in #memoryleakfix:memoryleakfix.mixins.json:tagKeyLeak.TagKey_internerMixin from mod memoryleakfix failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap memoryleakfix-common-1.17+-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	... 33 more
```

## Stack trace for `hugeScreenshotLeak`, `memoryLeakFix$captureByteBuffer` (Forge 1.19 〜 1.19.2)
```
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main$2.run(Main.java:158) ~[client-1.19.2-20220805.130853-srg.jar%23146!/:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method memoryLeakFix$captureByteBuffer(Ljava/nio/ByteBuffer;Lcom/llamalad7/mixinextras/sugar/ref/LocalRef;)Ljava/nio/ByteBuffer; in memoryleakfix.mixins.json:hugeScreenshotLeak.Minecraft_screenshotMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap memoryleakfix-common-1.17+-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar%2391!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.doPostInject(SugarWrapperInjectionInfo.java:131) ~[MixinExtras-0.2.0-beta.5.jar%23154!/:?]
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.postInject(SugarWrapperInjectionInfo.java:125) ~[MixinExtras-0.2.0-beta.5.jar%23154!/:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 14 more
```

**Comment by FxMorin** [comment]
We will look into this soon, thanks.
~~For now ill release another beta just to fix the other issues~~

**Comment by FxMorin** [comment]
Should be fixed in beta 6
